### PR TITLE
Remove typedef jsdoc for UNITS (fixes #127)

### LINKED ISSUE #127: Typescript thinks UNITS is a type-only export
When I try to use `h3.UNITS` in a Typescript project, I see
```
'UNITS' only refers to a type, but is being used as a value here.
```
Probably need to change the way the types are formatted to export a constant.

### PR DESCRIPTION
**Pull request by felix-kaestner**

### CODE REVIEW

**Comment by dfellis** [comment]
The last test is failing because the generated README after your change doesn't match the README you have committed: https://github.com/uber/h3-js/runs/5154080581?check_suite_focus=true

If you run `yarn build-docs` in the root of the project, it should mutate the README and then you can commit that to this PR as well.

**Comment by felix-kaestner** [comment]
@dfellis Thanks, the CI pipeline now successfully builds.

**Review by dfellis — APPROVED** [review]

**Comment by dfellis** [comment]
> @dfellis Thanks, the CI pipeline now successfully builds.

:+1:

I just requested the library owner @nrabinowitz to give a review, but I think this'll be a rubberstamp now :)

**Review by nrabinowitz — APPROVED** [review]
Thanks! This was on my list to fix.

**Pull request merged**
